id: PCF49A281
initial_creation_type: input
source_metadata:
  title: Gesar Series
  language: en
  description: 'A series of texts dedicated to the legendary warrior king Gesar (ge
    sar):'
  volume:
    14e5a5ff85fa41c5afa45b3051cd2769:
      title: Concerning Offering Rites to the Great Lion Gesar
      parent: Commentaries
    c9225e02246c443ab115f3c4fc15ccec:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Guru Yoga
    72bef8ff430b4d35b515f672c46325e2:
      title: Brief Gesar Windhorse Invocation
      parent: Lungta
    9518b2c80b814e38a9008ba9fa2f1ddc:
      title: Short Windhorse Prayer to Gesar
      parent: Lungta
    12b5d7c57acf4e5898f4049be8630d70:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Offering Rites
    fb58669ab9304fe788c04ecf40eb0b90:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Prayers
    343f66b789c049e58eb91806397de7c7:
      title: Brief Offering Prayer to Gesar
      parent: Prayers
    acf73de9cc274841b5b219d5581db9a3:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prayers
    007308c5ac674e1d887da09acece288b:
      title: Prayer to Gesar
      parent: Prayers
    7253e0787e88400ab0f2868d8c3e2a07:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Prayers
    9b1d5446b8d64b33915fb94818f4cfff:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Prayers
    67994be152a840859b613bc5d134694d:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Prayers
    b2f8a0f5872a43f99f28aa7e9628ae3b:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Sang Offering
created_at: '2022-03-01T03:43:17.452012'
last_modified_at: '2022-03-01T03:43:17.452018'
